# Generated by Django 4.2.5 on 2023-10-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_item_kelas_remove_item_nama_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
